# Generated by Django 2.0.6 on 2018-06-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yahoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningscalendar',
            name='is_confirmed',
            field=models.NullBooleanField(),
        ),
    ]
