# Generated by Django 2.0.6 on 2018-10-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yahoo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yahoosustainability',
            old_name='peer_high_controversy_performance_avg',
            new_name='peer_highest_controversy_performance_avg',
        ),
        migrations.RenameField(
            model_name='yahoosustainability',
            old_name='peer_high_controversy_performance_max',
            new_name='peer_highest_controversy_performance_max',
        ),
        migrations.RenameField(
            model_name='yahoosustainability',
            old_name='peer_high_controversy_performance_min',
            new_name='peer_highest_controversy_performance_min',
        ),
        migrations.AddField(
            model_name='yahoofinancialscashflow',
            name='issuance_of_stock',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='yahoofinancialscashflow',
            name='repurchase_of_stock',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='yahooholdersholders',
            name='position_combined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='yahooprofileassetprofile',
            name='err',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='yahooholdersinsidertransactions',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='yahoonews',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='yahooprofileassetprofile',
            name='fax',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='yahooprofileassetprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='yahooprofileassetprofile',
            name='zip',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='yahoostatistics',
            name='enterprise_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='yahoostatistics',
            name='market_cap_intraday',
            field=models.FloatField(null=True),
        ),
    ]
