# Generated by Django 2.0.6 on 2018-06-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yahoo', '0002_auto_20180627_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningscalendar',
            name='n_estimates',
            field=models.IntegerField(null=True),
        ),
    ]
